In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
from pandas import DataFrame

In [2]:
url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
result = requests.get(url)
doc = soup(result.text, "lxml")
items = doc.find_all('div', {'class': 'col-sm-4 col-lg-4 col-md-4'})
data1 = []

In [3]:
for item in items:
    data1.append({
        'Product' : item.a['title'],
        'price' : item.find('h4', {'class': 'pull-right price'}).string
    })

In [4]:
df = pd.DataFrame(data=data1)

In [5]:
df

                                        Product     price
0                    Asus VivoBook X441NA-GA190   $295.99
1            Prestigio SmartBook 133S Dark Grey   $299.00
2                 Prestigio SmartBook 133S Gold   $299.00
3                                 Aspire E1-510   $306.99
4                             Lenovo V110-15IAP   $321.94
..                                          ...       ...
112                          Lenovo Legion Y720  $1399.00
113               Asus ROG Strix GL702VM-GC146T  $1399.00
114               Asus ROG Strix GL702ZC-GC154T  $1769.00
115               Asus ROG Strix GL702ZC-GC209T  $1769.00
116  Asus ROG Strix SCAR Edition GL503VM-ED115T  $1799.00

[117 rows x 2 columns]

In [6]:
price_value = df['price'].str.extract('(?P<price_value>\d+)',expand=False)
df['price_value'] = price_value.astype('int')

In [7]:
price_value

0       295
1       299
2       299
3       306
4       321
       ...
112    1399
113    1399
114    1769
115    1769
116    1799
Name: price_value, Length: 117, dtype: object

In [8]:
df

                                        Product     price  price_value
0                    Asus VivoBook X441NA-GA190   $295.99          295
1            Prestigio SmartBook 133S Dark Grey   $299.00          299
2                 Prestigio SmartBook 133S Gold   $299.00          299
3                                 Aspire E1-510   $306.99          306
4                             Lenovo V110-15IAP   $321.94          321
..                                          ...       ...          ...
112                          Lenovo Legion Y720  $1399.00         1399
113               Asus ROG Strix GL702VM-GC146T  $1399.00         1399
114               Asus ROG Strix GL702ZC-GC154T  $1769.00         1769
115               Asus ROG Strix GL702ZC-GC209T  $1769.00         1769
116  Asus ROG Strix SCAR Edition GL503VM-ED115T  $1799.00         1799

[117 rows x 3 columns]

In [16]:
df_new = df.drop(['price'],axis=1)
df_new

                                        Product  price_value
0                    Asus VivoBook X441NA-GA190          295
1            Prestigio SmartBook 133S Dark Grey          299
2                 Prestigio SmartBook 133S Gold          299
3                                 Aspire E1-510          306
4                             Lenovo V110-15IAP          321
..                                          ...          ...
112                          Lenovo Legion Y720         1399
113               Asus ROG Strix GL702VM-GC146T         1399
114               Asus ROG Strix GL702ZC-GC154T         1769
115               Asus ROG Strix GL702ZC-GC209T         1769
116  Asus ROG Strix SCAR Edition GL503VM-ED115T         1799

[117 rows x 2 columns]

In [20]:
df_final = df_new.rename(columns={'price_value':'Price ($)'})
df_final

                                        Product  Price ($)
0                    Asus VivoBook X441NA-GA190        295
1            Prestigio SmartBook 133S Dark Grey        299
2                 Prestigio SmartBook 133S Gold        299
3                                 Aspire E1-510        306
4                             Lenovo V110-15IAP        321
..                                          ...        ...
112                          Lenovo Legion Y720       1399
113               Asus ROG Strix GL702VM-GC146T       1399
114               Asus ROG Strix GL702ZC-GC154T       1769
115               Asus ROG Strix GL702ZC-GC209T       1769
116  Asus ROG Strix SCAR Edition GL503VM-ED115T       1799

[117 rows x 2 columns]

In [21]:
df_final['Price ($)'].mean()

908.9230769230769